### ISSUE TITLE
Add Sponge support

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#1]
Just a reminder, so I can work on Sponge support

**Comment by EmanYm** [comment]
Is this ready for beta stage?  I want to try and recreate an old project I had going on VT1.7.10.

**Comment by EmanYm** [comment]
There might be help [coming your way](https://forums.spongepowered.org/t/trigger-reactor-dev-looking-for-help/20053)...

**Comment by wysohn** [comment]
Sweet! Thanks for your effort :)
