### ISSUE TITLE
Add line break (\n) escape for string

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#105]

**Comment by Alex4386** [comment]
Is it possible to implement Carrige Return Character (\r) for strings either?

**Comment by Alex4386** [comment]
Never Mind, Will work for PR instead.

**Comment by wysohn** [comment]
> Never Mind, Will work for PR instead.

Thank you!

**Comment by Alex4386** [comment]
Isn't this issue resolved?

**Comment by wysohn** [comment]
It's merged but not deployed yet. I will release the final version soon

**Comment by Alex4386** [comment]
OK, Thanks for the reply. :)
