### ISSUE TITLE
bug with AreaTrigger

### ISSUE THREAD

**Issue by JohnNa87** [wysohn/TriggerReactor#12]
Hey wysohn its me again...I was keep changing the coding values (to add color to a message and etc)
suddenly the trigger stopped working in fact... the area I set up for my test moved away.
I tried to delete the area and set new area (on the same xyz coordinates I used) but it keeps doing it.

For example, X=100 but triggers on when X=120 
After having this problem I've done everything like deleting the plugin and resetup, I even tried to change
the region on Areatrigger.yml but still.... is it because that I use the 1.12 version perhaps?
please tell me how to fix this... Thanks

**Comment by wysohn** [comment]
Do you see any errors?

Without the procedures or screenshots, I can't really find what's going on

**Comment by JohnNa87** [comment]
![error](https://user-images.githubusercontent.com/29798911/27752212-cecd0426-5e1a-11e7-9fa4-bb4784790e58.png)
idk what information u need if you need anything further jst let me know

**Comment by wysohn** [comment]
Hmm very weird

Let me test it in my side and see what's going on

**Comment by JohnNa87** [comment]
something that you need to keep in mind is that it used to work but after series of tests 
(right exactly where I start to put in the color code), it starts to make this error.
Maybe because I kept /trg reload, /trg saveall all the time I try to implement the code?

should I delete all minecraft related programs and reinstall them all? idk... :'( 
I can op you in my server and try them if you want to its temporary server with dynamic ip anyway
its 203.132.181.87

**Comment by wysohn** [comment]
Doesn't restarting the server fix the problem?

I have a little assumption what is causing it, but it should be fixed on server restart if that's the case

**Comment by JohnNa87** [comment]
nope I've restarted my server more than 10 times now :'(

**Comment by wysohn** [comment]
No error at all on the console? This is confusing situation.

You might wanna consult the latest.log or something to see if you missed anything

it might can show something on start up, but it could be passed away too fast

**Comment by wysohn** [comment]
Wait, did you download the one on the jenkins?

These version is not tested and can cause problem

**Comment by JohnNa87** [comment]
I'm sure its either from dev or curse I will re download the plugin from the dev and try it once more but 
I'm having this problem only on specific xyz coordinate in my server other area works fine..

**Comment by wysohn** [comment]
That's very very odd

Or may some other plugin is stealing the event so TriggerReactor can't detect it

worldguard region or something maybe?

if it's working for other area triggers, something other might be interfering with it

it can be bug of plugin too, but I can't think of anything yet

**Comment by JohnNa87** [comment]
yeah... nope... I've removed all the plugins except for EssentialsX/Worldedit/TriggerReactor and it keeps on doing the same things.... based on the fact that it used to work (before something happened) I think the
test I was implementing must corrupt some file idk the spigot? or maybe map itself? (and also the other regions works fine means this can be true...; the map that was corrupted)

**Comment by wysohn** [comment]
Yeah it's very difficult situation

if it doesn't work for all the area, then something is happening in the plugin

All it does is get area saved in the chunk location, so as long as it has proper chunk location, it should work.

More weird thing is that it worked for you for awhile..

Does the event even firing?

try put #LOG "Fired" at the top of Enter script and see if it shows "Fired" on the console

if it does, then something is not working inside the script

**Comment by JohnNa87** [comment]
wysohn... I think I found the problem ..... it was related with essentialX plugin... 
when I reload the essential it kept saying reload may cause some problems but I wasn't sure if it may
cause it was fine till the last time I reloaded it. I'm sorry to take so much of your time. and thanks for your help :'(

**Comment by wysohn** [comment]
So you found the problem! Great!

There is nothing to sorry about. I appreciate your time to solve the problem :)

Make another issue anytime if you have other troubles

**Comment by JohnNa87** [comment]
Thanks a lot for your concerns :). I know that it is hard to implement a simple Java project .. but complicated ones like yours.... I admire your ability.
