### ISSUE TITLE
the /trigger alias for /triggerreactor Overrides vanilla minecraft's /trigger command

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#143]
The plugin defines /trigger as an alias for /triggerreactor, however, this name is already taken by the [/trigger command](https://minecraft.gamepedia.com/Commands#trigger)  in vanilla minecraft as of minecraft 1.8.
Please consider removing this alias so the vanilla /trigger is once again available.

**Comment by wysohn** [comment]
3ad67716b06b1529c7bf9afed1e636f1db5ed01e
