### ISSUE TITLE
constructor calling need some revamp

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#178]
IMPORT java.io.File
IMPORT java.io.IOException
file = File("plugins" + File.separator + "TriggerReactor" +File.separator + "hello.txt") 
IF file.exists() 
    IMPORT java.io.FileReader
    IMPORT java.io.FileWriter
    IMPORT java.lang.System
    writer = FileWriter(file)
    reader = FileReader(file)

---

This code is expected to be work, but the FileWriter(file) would throw java.lang.IllegalArgumentException: argument type mismatch.

Most likely the wrong constructor was found in the searching process.

**Comment by gerzytet** [comment]
implemented in release 2.2.0
