### ISSUE TITLE
Check is plugin in loaded before use.

### ISSUE THREAD

**Issue by miresru** [wysohn/TriggerReactor#182]
Hi!

I am trying to make my own plugin.
And I want to use some methods of my plugin from TR.

I can run method using `plugin("myplugin").myMethod()`.
But how I can check is my plugin loaded and ready to use?

**Comment by wysohn** [comment]
Hi, thank you for your interest!

the plugin("myplugin") method returns the plugin object only if the plugin is actually loaded.

Otherwise it is null

So may do something like

mp = plugin("myplugin")
IF mp != null
    mp.myMethod()
ENDIF

**Comment by miresru** [comment]
Thanks a lot! :-)
