### ISSUE TITLE
File tree doesn’t belong in the README

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#189]
The file tree in README.md is out of place for the following reasons:

1. **irrelevant to the readme file**.  Since the README file is meant to give an overview of the project, a detail like an extensive chart of the file layout is not relevant, nor is it helpful when using the plugin.
2. **difficult to maintain**.  To keep the file tree up to date, every rename, deletion, and addition of a file will require changing the readme.  Because of this, the development branch file tree is *already* outdated.  What’s the point of keeping around outdated information?
3. **who would use it?**. Users sure wouldn’t, and contributors will simply search the repository for the files they need.

The file tree should either be replaced by the file structure of the TriggerReactor plugin storage folder, which is much smaller and could be of use to users, or should be removed entirely.

**Comment by wysohn** [comment]
Agreed, will make some change soon.

Probably some kind of UML diagram would be much better

**Comment by gerzytet** [comment]
UML wouldn’t be more helpful, just make sure it doesn’t end up in the readme

**Comment by wysohn** [comment]
f4617f6ea9f40be24fbf37016521c0084c64d744

**Comment by gerzytet** [comment]
Done
