### ISSUE TITLE
Unexpected Error occurs on 1.14.4

### ISSUE THREAD

**Issue by rkdrns4747** [wysohn/TriggerReactor#197]
https://pastebin.com/8sj6Fvsw

https://pastebin.com/Z0wuSzgz

Two(or more) of users got this error while using TR on their 1.14.4 server. They used TR-latest one, so It's maybe something doesn't go well.

**Comment by gerzytet** [comment]
What happened right before the error?
What happened to cause it?

**Comment by rkdrns4747** [comment]
@gerzytet 
they both added their spigot 1.14.4 plugin, and first type '/trg c'. Then that error occured.

**Comment by wysohn** [comment]
@rkdrns4747 
It seems the plugin is not properly loaded

But I can't tell until I see the actual full log of it happens

One of my suspicions is that they are running Spigot with Java version higher than 1.8

We do not support the Java, version higher than 1.8, yet

**Comment by rkdrns4747** [comment]
@wysohn I see. I'll check their Java version.

**Comment by gerzytet** [comment]
@rkdrns4747 
Has this been resolved?

**Comment by rkdrns4747** [comment]
@gerzytet @wysohn 

https://pastebin.com/1mSwJ3ri

someone noticed same error but he said he use java 8. I think this is not an error by wrong java version.

**Comment by wysohn** [comment]
@rkdrns4747 
That's still the same error message. It's the stack trace of Exception thrown when a user trying to execute /trg command while the plugin is disabled.

We have to know what caused the plugin to not load properly, and that's usually noted at the very top of the latest.log file.

**Comment by rkdrns4747** [comment]
@wysohn maybe this is right one
https://pastebin.com/g66m5WKg

**Comment by wysohn** [comment]
Indeed, that's the problem

**Comment by rkdrns4747** [comment]
@wysohn I found that same error occurs in version 3.0.0 beta.
