### ISSUE TITLE
NamedTrigger sync/async

### ISSUE THREAD

**Issue by soliddanii** [wysohn/TriggerReactor#20]
Hello, wyshon.

Congratulations on the progress you have been making with the plugin. 😄 

I don't know if it's just me but I'm experiencing a behaviour oposite to the one described by the changelog in _spigotmc.org_. Using version 1.2.4.

From the changelog:

> Now Named Trigger can be specified sync/async on run-time. #CALL "SomeNamedTrigger" true for sync, and #CALL "SomeNamedTrigger" false for async. Not providing second parameter will set it to be true(sync) by default.

I tryed executing a named trigger with no second parameter and the execution was asyc. I know that because i got a bunch of errors related to trying to edit the world asynchronously (Do you remember #14 ?). If i set the second parameter as true, same thing happens  ( **/trg run #CALL "namedTrigger" true** ).

If I set the parameter as false ( **/trg run #CALL "namedTrigger" false** ), the named trigger executes sync and everything works fine. Just oposite to the changelog description.

Thank you 👋

**Comment by wysohn** [comment]
That's pretty odd

I should check it

**Comment by soliddanii** [comment]
This is really weird. I use:

    /trg run #CALL "test" true

And test NammedTrigger is: 

    #WORLD:FALLINGBLOCK 5, 1, -14331, 27, -1748
    #WAIT 1

And I get an async spawn of entity bla bla bla error.
Then I edit the executor to use the scheduler, so I can use it from async mode.

Execute the exact same command and get a:

#WAIT is ilegal in sync mode! error..... wait what? I thought I was in async??

So I change to 
    /trg run #CALL "test" false

and everything works fine....

This is so weird. I dont't know wether I'm using sync or async mode.

**Comment by wysohn** [comment]
Still working on it.

**Comment by wysohn** [comment]
7769a19e65bf8373ad94b0a1c7f97ad88105af45

Probably fixed in the latest update.

Let me know if weird things happen
