### ISSUE TITLE
unify warnings system

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#200]
Happy 200th issue!

Currently, we have 2 ways of warning users:
1. The message that appears when an admin runs a trg command.
2. The warnings system in the console.

Having both may be unnecessary.
After all, many users won't be affected by string interpolation changes, since they don't use $ in their strings.  For them, seeing the message every time will get old fast.  The warnings system only targets people who have an actual issue, so I think that it should be the only one.

**Comment by wysohn** [comment]
I didn't really go through every single part of the Deprecation Warning System, so I can't really tell which one would be a more suitable solution.

My only concern is that the Deprecation Warning System might spam the console if the Trigger using the deprecated Executor, and the Trigger is some kind of repeatedly executed type(like Repeat trigger or using loops, etc.)

I have no problem getting rid of option 1. if the spamming is not the case.

**Comment by gerzytet** [comment]
currently, warnings only appear during parsing.  There should only be a problem if for some reason a repeating trigger gets parsed every time it is activated

**Comment by wysohn** [comment]
Sounds good to me.

**Comment by gerzytet** [comment]
closing this since it's done, thanks!
