### ISSUE TITLE
Add support for numerical gamemodes for #SETGAMEMODE

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#207]
for example, #SETGAMEMODE 0 should be equivalent to #SETGAMEMODE "survival"

benefit: more concise code without losing readability, since these numbers are widely understood

**Comment by wysohn** [comment]
@rkdrns4747 
Assign yourself for the task next time, so we know that you are working on it

Also, Milestone if applicable :)

**Comment by rkdrns4747** [comment]
@wysohn kk. I'll do the things from next time.

**Comment by gerzytet** [comment]
Closing this since it’s been released in 2.2
The 3.0.0 milestone is incorrect.
