### ISSUE TITLE
[Suggestion] Add support for arguments in command triggers

### ISSUE THREAD

**Issue by soliddanii** [wysohn/TriggerReactor#21]
I believe that right now you can't create a command trigger that takes arguments. Can you please add this feature? 😄

**Comment by wysohn** [comment]
You can take arguments in fact :)

CommandTrigger has its own variables that hold the arguments


Variables | Link
-- | --
command | String -- it's the actual command string
args | Array -- the arguments that the player have entered. args[0] for first argument, args[1] for second, ...
argslength | Number -- number of argumenets. Equivalent to args.length

**Comment by soliddanii** [comment]
Thank you very much 😄 
For some reason I couldn't find it in the wiki.

**Comment by wysohn** [comment]
Yeah current wiki has a little low readability c.f.

I would appreciate if you fix it a little if you want to :p

**Comment by DontActLikeMe** [comment]
can you provide an example of how i could take arguments? i see that you have args but idk how to type the command

**Comment by wysohn** [comment]
The args is the Array of String, so to access the values in it, you need the square bracket.

For example, if you would need the first argument of the command, simply use args[0]

    #MESSAGE args[0]

This will print out 'boom' if you have a command trigger 'test,' and typed something like /test boom.

But be aware of that the number you put there can be out of bound depends on how many arguments are originally passed to the Trigger.

You can check that by using argslength variable, or args.length.

    IF args.length > 1
        ....
    ENDIF

This will make sure that there is at least one argument before executing the command

You may find this wiki useful too: https://github.com/wysohn/TriggerReactor/wiki/Array

**Comment by DontActLikeMe** [comment]
i actually figured it out lol while waiting for you XD but thank you so much. this will definitely help others along the way! i actually designed a command that lets you make other players say whatever you want XD
