### ISSUE TITLE
Finish 2.2 Korean documentation

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#210]
[Here](https://github.com/wysohn/TriggerReactor/wiki/Executors/_compare/8f8bae95570cbfbe520a8c84c78aac2df6272f1e...287c5f3a1daa4987bd4abe49efb21e7f830d135e) are all the changes in the Executor documentation as a result of the 2.2 update.
All changes below line 47 need to be translated into Korean
(The changes above 47 were all for clarity and didn’t add/remove information)

**Comment by gerzytet** [comment]
As far as I can tell, the information has been added.

**Comment by rkdrns4747** [comment]
I reviewed it, but need some edit.

**Comment by rkdrns4747** [comment]
done
