### ISSUE TITLE
Why do we have anything at all assigned to 3.0.1?

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#216]
It’s common practice for versions that change the last number of the release to be bug-fix only releases.
Minecraft itself does it this way.  Releases like 1.8 have features, but 1.8.1 and all the ones after that until 1.9 are only there to fix issues.
It should be assigned to 3.1 or 3.0 instead

**Comment by wysohn** [comment]
Sure, let's set the standard that way.

For major changes, the first digit, for minor updates, second digit, and the last digit is for bug-fixes.

**Comment by wysohn** [comment]
@gerzytet 
Feedbacks are welcome

5b76b3a5c7bab193d785f859faf344338bd5fd5e
