### ISSUE TITLE
link to CommonFunctions documentation is broken

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#218]

**Comment by gerzytet** [comment]
where?

**Comment by gerzytet** [comment]
Also, I understand if you're looking for a good example of a bug that you can add to the Bugs project, but this one is really tiny.
Does deserve an issue?  Does is deserve the bug label?
I could name off several places where the wiki is missing some info.  are those bugs?

**Comment by wysohn** [comment]
@gerzytet 
Each card(issue) serves as a reminder and also a job to do.

I would say it's a bug of the website since the link is dead when it shouldn't. We do have the Javadoc for CommonFunctions, yet the website just doesn't show it anymore. I will have to investigate what is going on.

Wiki is different in missing information, not the link to the existing information is broken.

**Comment by wysohn** [comment]
https://wysohn.github.io/io/github/wysohn/triggerreactor/bukkit/manager/trigger/share/CommandFunctions.html#color-java.lang.String-

It seems the website itself is working. Maybe it's just an invalid link

**Comment by rkdrns4747** [comment]
I've removed the link from Inventory-Trigger_kr document, cuz It's unnecessary and exists only in korean one.
