### ISSUE TITLE
Beta tag is confusing

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#222]
If an issue has the labels "Beta" and "bug", does this mean that it's a bug in beta, or a bug that's been fixed in beta?
If an issue has the labels "Beta" and "enhancement", does this mean that the enhancement is planned for beta, or the enhancement is done and it's in beta?

"Beta" doesn't tell us whether or not a feature is done, which is the most important piece of information an issue should have in its tags.
Can you define for us what the proper use of Beta is @wysohn ?

**Comment by wysohn** [comment]
The better way to distinguish them will be Projects or Milestone. 

I would prefer Projects since that's what I use to manage the backlogs.

And it will be also clear to see where it belongs since it has the exact version written on it. Each Kanban board has its own Testing (same as `done in development`) and Beta.

**Comment by gerzytet** [comment]
@wysohn 
I can't see the project/milestone progress from the issue overview to distinguish it though.
We need to agree on something so that I can see which issues are done without having to look inside each one

**Comment by wysohn** [comment]
@gerzytet 
Don't look at the issue overview. Look at the Kanban board. It's more straight forward.

https://github.com/wysohn/TriggerReactor/projects

**Comment by wysohn** [comment]
Each issue in the issue overview is one card in the Kanban backlog (tasks to do).

Not only it's easy to organize backlogs, but also we can perform tests according to the cards.

**Comment by wysohn** [comment]
You may find it interesting to read: https://www.atlassian.com/agile/kanban/boards

**Comment by wysohn** [comment]
@gerzytet @rkdrns4747 
Also, can I suggest getting rid of Beta and Done in Progress tag and the milestones? We really don't need them at this point, and it's just confusing to have them.

For grouping the versions, let's use the Projects (Kanban board) and use tags only to specify the category of the issue.

**Comment by wysohn** [comment]
@gerzytet @rkdrns4747 
Bump
