### ISSUE TITLE
Fix tr’s item manipulation weakness

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#224]
Tr’s executors and placeholders are strong in many areas, but they lack ways to work with items.
The problem is that we offer access to items and information about those items, but *always at the same time*.
For example, $helditemid can get the held item and find its ID but you can’t use the held item somewhere else and you can’t find the ID of a different item.
The solution is to split it into 2 separate placeholders: $id:{item} and $helditem
Similar splits need to happen for other placeholders and executors.

Some other functionality is missing altogether and splitting existing executors won’t fix it.
Here’s a list of executors and placeholders that would be necessary to support the most common uses of items (that I know of):
**Placeholders**:
General:

- [x] - $helditem
- [x] - $offhanditem
- [x] - $playerinv:{slot}
- [x] - $id:{item}
- [x] - $name:{item}
- [x] - $lore:{item} (returns the whole lore as a multi line string)
- [x] - $idname:{item} (the material name)
- Inventory trigger:
- [x] - $slot:{index} (preparing for #191 )

**Executors**:
General:

- [x] - #sethelditem {item}
- [x] - #setslot {slot}, {item}
- [x] - #setoffhand {item}
- [x] - #setplayerinv {slot}, {item}
- [x] - #setlore {lore}, {item}
- [x] - #setname {name}, {item}
- Inventory trigger:

You may be tempted to put this off until 3.1 or later, but I believe this deserves to be added to 3.0.  So far, the biggest accomplishments for 3.0 have been:
- /trg timings, from wysohn
- the PAPI extension, from pro_snape
- executor validation, from me

All of these only benefit users doing very specific things.
However, lots of users ask about item manipulation, since it’s a common use case.

**Comment by wysohn** [comment]
Sounds good since we will have to add Trigger specific Executors and Placeholders (#163), so we can do this alongside the new Executors and Placeholders.

But we will have to finish the validation system first

**Comment by wysohn** [comment]
@rkdrns4747 
Which of the listed items are done? Is #229 addressed?

I'm trying to wrap up everything for 3.0.0, so let me know the progress.

**Comment by rkdrns4747** [comment]
@wysohn 
I finished all unit tests each. However, $playerinv, $slot, #SETPLAYERINV, #SETSLOT weren't implemented in sponge since I have no idea how to set/get item on specific slot.
If these things are implemented and tested in-game, everything is done.

**Comment by wysohn** [comment]
@rkdrns4747 
Nice, I will cover that part. It is indeed kind of complex since Sponge team still do not have documentation of how inventory system work. It's somewhat hard to explain too anyway.

**Comment by rkdrns4747** [comment]
@wysohn Are they test-required?

**Comment by wysohn** [comment]
@rkdrns4747 
I've done the non-functional testing with the Sponge server open, but you are free to test it on your own.

More test is always better.

**Comment by rkdrns4747** [comment]
@wysohn alright
