### ISSUE TITLE
Server restart required to activate new custom trigger using onBlockBreak 

### ISSUE THREAD

**Issue by gmalone** [wysohn/TriggerReactor#228]
Turns out a server restart is required to get the onBlockBreak event to work in a newly created custom trigger.  A /trg reload was not enough. 

I was asked to submit this as an issue.

**Comment by wysohn** [comment]
@gmalone 
Cannot reproduce it. Have you tried with debugging code? (For example, try put #MESSAGE at the very top of the .trg file)

Tested on both 1.14.4 and 1.14.4-paper server, but it works without /trg reload

---
Case 1
Create .trg and .yml manually and restart the server.
Break the block immediately to confirm

Case 2
Create custom trigger with /trg custom onBlockBreak testBlockBreak #MESSAGE "blockBreak"
Break the block immediately to confirm
---

Let me know if you found how to reproduce the case.
