### ISSUE TITLE
changing letter in later release?

### ISSUE THREAD

**Issue by Alex4386** [wysohn/TriggerReactor#24]
This can be a very harsh chellenge but can you change the letter "#" into another letter since # is for a commenting in the yml language.

(Sorry about my poor english)

**Comment by wysohn** [comment]
Hmm but is there any case that you have to load TriggerReactor codes into Yaml parser?

If that's not the case, it shouldn't be something to worry about.

Are you experiencing any discomfort because of the # sign? Let me know with some details if you are.

**Comment by Alex4386** [comment]
Well. I am usually using VS Code to edit some yml files. but the editor takes it as a comment. and it causes some discomfort.

(And It seems you are native korean though. If you don't care about it, Is it ok to talk about this issue in korean?)

**Comment by wysohn** [comment]
I would suggest you to use notepad++ instead of VS.

This is the language didn't meant to be used with yml even though it uses yml at some part.

(And yes, whatever language you feel comfortable with :D)
