### ISSUE TITLE
[Suggestion] Indentation in in-game editor

### ISSUE THREAD

**Issue by soliddanii** [wysohn/TriggerReactor#25]
It's a silly  suggestion. Could you add a 0 or a blank space in front of the first 9 line numbers of the in-game editor, so when the 2 digit starts the indentation isn't shifted to the right?
See image for easy understanding. 

![In-game editor](https://i.imgur.com/Sn8VqDh.png)

Thank you 😅

**Comment by wysohn** [comment]
73249ec

Added

(It's not silly suggestion though; it's enhancing the user experience!)
