### ISSUE TITLE
Escape characters?

### ISSUE THREAD

**Issue by Alex4386** [wysohn/TriggerReactor#26]
Hi. I am trying to use TriggerReactor in personal server right now
is there any escape letter for `"`?

I need to make the trigger that codes like
```
#CMDCON "title "+args[0]+" ["",{"text":""+args[1]+"","color":"gold"}]"
```

**Comment by wysohn** [comment]
You got on the point!

I was thinking about it too.

**Comment by wysohn** [comment]
bac920e547227875fc6d5dcdb30e34a2e708f60c
