### ISSUE TITLE
How to create/change local and global varibles from Executor?

### ISSUE THREAD

**Issue by miresru** [wysohn/TriggerReactor#28]
How I can create or change local or global varible from Executor?

For example I have script:
`{"myobj.myvar"} = "some data"`
`#TEST "new data"`
`#LOG {"myobj.myvar"}`

How I can change `myobj.myvar` in  TEST.js?

**Comment by miresru** [comment]
I found sollution, but I am not sute it's right one.

Script file:
`{"myobj.myvar"} = "some data"`
`#TEST "NEW DATA"`
`#LOG {"myobj.myvar"}`

TEST.js
`function TEST(args){`
`plugin.getVariableManager().put("myobj.myvar",args[0]);` - to set global var
`plugin.getVariableManager().saveAll();` - to save vars to file
`var v = plugin.getVariableManager().get("myobj.myvar");` - to get global var
`print("v="+v);` - print it to console
`return null;`
`}`

For all other methods look here: [VariableManager](https://wysohn.github.io/io/github/wysohn/triggerreactor/manager/VariableManager.html)

**Comment by wysohn** [comment]
great that you are accessing VariableManager directly!

though, there is a predefined functions: get(String), put(String, Object), and has(String)

they do the exact same thing as you are doing now.
