### ISSUE TITLE
Enhancement Request Scripting Inventory Trigger Icons

### ISSUE THREAD

**Issue by DontActLikeMe** [wysohn/TriggerReactor#32]
As the title says. I know your busy but i think this would be so cool. An example of this is, i could use your common function getPlayers() and loop through them to make icons for each player in an inventory.Then i could have it do something if i click on a particular player.

**Comment by wysohn** [comment]
So do you mean like using player head?

That can be a thing

Not sure what you are trying to do here though.

Adding that to CommonFunctions would be amazing

**Comment by DontActLikeMe** [comment]
Yes definitely getting the player head. I like that you like my idea XD

**Comment by wysohn** [comment]
Will definitely add that soon

**Comment by wysohn** [comment]
Probably I can add something like a custom head generating with the base64 value thingy too.

That will require some nms, so maybe

**Comment by wysohn** [comment]
b51a6ae1a3c86dce70f79e8112c22ebe673e9c67
b42507e63107277c8323f2f0d3d7ee6a017054b9
