### ISSUE TITLE
Trigger Reactor 1.3.3 Issue - Seemingly with a while loop

### ISSUE THREAD

**Issue by DalekCaan2** [wysohn/TriggerReactor#33]
Hello, I recently updated a server I administrate to Trigger Reactor version 1.3.3, I found out earlier today that some of our commands broke, so I decided to investigate and found an "ENDWHILE" was causing this error: https://gyazo.com/2c906cbd7f598ebeae119491239c539f (this was tested by adding in messages in the code eg; #MESSAGE "Debug"). After reverting to version 1.3.2 the command worked perfectly again. Here's the code:
(All variables are named above, I just pasted in the main bit around where the error seemed to come from)

AllowPurchase = "no"
	splitprefix = mergeArguments(args).split(" ")
	number = 1
	WHILE number < 17
		IF splitprefix[0] == validcolours[number]
			AllowPurchase = "yes"
				number = 17
		ELSE
			number = number + 1
		ENDIF

	**ENDWHILE**

	IF splitprefix.length > 1

**Comment by wysohn** [comment]
Thank you for the detailed report!

I will fix this soon as I find what's the issue.

**Comment by wysohn** [comment]
cb10cf7934f604bb06e8c6875f91f729d79b0759

Should be solved in http://104.199.115.214:8080/job/TriggerReactor/
