### ISSUE TITLE
Replacement of <cmdarg> in VT?

### ISSUE THREAD

**Issue by SamaineS2** [wysohn/TriggerReactor#35]
In VT(VariableTriggers), there is a placeholder called <cmdarg>.
I wanted to ask if there is a placeholder in Trigger Reactor that can replace this.
cmdarg is a placeholder that can detect the second arg of the command...
such as if I do the command "/event" then I will say [IF the cmdarg:1 is null, then]
which is in the statement [@IF <cmdarg:1> = null]
 
so.
If you still dont get it...
It is simply the second part of the command.
It detects after the main command;
/event go < it detects this.
 
So, here is an example.
I will type the command "/event"
Then it will show &aHi!
I will type the command "/event go"
Then it will warp me to "event"
 
So, simply in conclusion, I want to ask if there is a way to detect
"/event go" or the line after the main command. such as "/event help"
So it can give diffrent outputs.

**Comment by DontActLikeMe** [comment]
This was answered in an earlier thread. You can in-fact take arguments on a command trigger.All you have to do is check for arguments. The first argument after the command is args[0]
``IF argslength >=1
IF args[0] == (whatever you need it to equal or be)
(whatever you need it to do)
ENDIF
ENDIF"
You can take more than one argument with this format as well you just have to check for them.
