### ISSUE TITLE
SOUNDALL doesn't work properly

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#6]
A user reported that only a player can hear it

**Comment by soliddanii** [comment]
I changed:

    player.playSound(location, sound, volume, pitch);

to

    location.getWorld().playSound(location, sound, volume, pitch);


It worked, you can try that 👍

**Comment by wysohn** [comment]
Amazing work!

You might wanna create a PR so I can merge it to the main branch :)
