### ISSUE TITLE
#OPENDOOR and #CLOSEDOOR incorrect Z coordinate

### ISSUE THREAD

**Issue by MidnightSugar** [wysohn/TriggerReactor#65]
There is a bug with #OPENDOOR and #CLOSEDOOR. The Z coordinate is one off. If I want to open a door at Z10 I have to set it to Z9.

**Comment by wysohn** [comment]
Will work on it soon

@soliddanii you still there though? :p

**Comment by soliddanii** [comment]
Is the bug solved? If it isn't im sorry but I don't have the time to take a look at it :')

**Comment by MidnightSugar** [comment]
Yes, it turns out that I was using XYZ instead of blocks in F3. XYZ counts the distance from origin, and I found out that origin is actually the corner of a block. So sometimes it is one off. The block section in F3 is accurate.
