### ISSUE TITLE
Add configuration option to change Executor prefix

### ISSUE THREAD

**Issue by soliddanii** [wysohn/TriggerReactor#7]
Default prefix beeing #

**Comment by wysohn** [comment]
Had been thinking about this, but it can be a trouble maker as using ambiguous character will fail the whole script. (For example, if someone set Executor character as +, you know what will happen)

**Comment by soliddanii** [comment]
I know. What if you just allow a handfull of symbols. I just wanted to use @ as i was used to it :(

**Comment by wysohn** [comment]
Hmm maybe we can use both @ and #

But I wanted to avoid any hassle caused by using same symbol as variable triggers

Although I started this project thinking to revive the VT, it's whole new structure right?

Or do you think it will be specifically easier to use @ than # sign?

**Comment by soliddanii** [comment]
Nah, I think it's just a matter of preference. Leaving it as it is is perfectly fine.
