### ISSUE TITLE
Placeholder - Special [$random]

### ISSUE THREAD

**Issue by TK742** [wysohn/TriggerReactor#73]
Small grammatical mistake here.
Use `$random:1:6` instead of `$ramdon:1:6` 

Placeholder | Type | Remark
-- | -- | --
$random:{Number} | Number | #MESSAGE "From 0 to 5: "+$random:6
$random:{Number}:{Number} | Number | #MESSAGE "From 1 to 6: "+$random:1:7
$currenttimeseconds | Number | Get epoch time(time passed since Jan 1st, 1970) in seconds.

@wysohn

**Comment by wysohn** [comment]
Can't replicate the problem

Just tested this code working

/trg run #MESSAGE "From 1 to 9: "+$random:1:10
