### ISSUE TITLE
Add command to run Executors

### ISSUE THREAD

**Issue by soliddanii** [wysohn/TriggerReactor#8]
Kind of like a test command, so we don't have to delete and create a command trigger every time we test the same executor with different parameters. 

Command idea: /trg execute[exec] #EXECUTOR
Example: /trg exec #MESSAGE "Hi"

**Comment by wysohn** [comment]
It might be better to make it work as temporary Command Trigger.

So for example, /trg run [codes...]

This will not save anything but run one time code execution as Command Trigger

    /trg run #EXECUTORTOTEST blah blah

or

    /trg run player.sendMessage("Message to yourself")

This will be able to accept more broad range of codes to test.

---------------------------------------------------------------------------------

Just a small tip: you can format the code in Github by putting four spaces before the line.

spacespacespacespaceMyCode...

**Comment by soliddanii** [comment]
Great idea, and thanks for the tip.

**Comment by wysohn** [comment]
Added in 745473d6339fb35d75d7e7de1f8a520795a95862
